const dataRoastedСoffee = [
    {
        num: 5,
        reviews: 9,
        acidicLvl: 9,
        bitterLvl: 5,
        saturatedLvl: 6,
        title: 'Colombia Supremo',
        subtitle: 'Мытая, натуральная, смесь',
        toastingLvl: 4,
        id: 4,
        listOptions: [
            { optionValue: 250, price: 150 },
            { optionValue: 500, price: 500 },
            { optionValue: 1000, price: 1000 },
        ],
        geography: 'Йемен',
        special: 'Новый урожай',
        typeOfCoffee: 'Арабика',
        imgSrc: '/images/catalog/roastedCoffee/image.png',
        imgFull: '/images/catalog/roastedCoffee/imageFull.png',
        description: 'Компания Нью Рефайнинг Груп находится в г. Калининграде и имеет свой склад и представительство в Москве.Завод работает на рынке свежеобжаренного кофе и растворимой продукции более 15 лет.Завод имеет немецкое оборудование марки Probat по обжарке кофе и итальянские агломераторы для производства растворимой продукции.',
    }, {
        num: 5,
        reviews: 9,
        acidicLvl: 7,
        bitterLvl: 5,
        saturatedLvl: 6,
        title: 'Colombia Supremo',
        subtitle: 'Мытая, натуральная, смесь',
        toastingLvl: 4,
        id: 5,
        listOptions: [
            { optionValue: 250, price: 350 },
            { optionValue: 500, price: 500 },
            { optionValue: 1000, price: 1000 },
        ],
        geography: 'Йемен',
        special: 'Ваш выбор',
        typeOfCoffee: 'Арабика',
        imgSrc: '/images/catalog/roastedCoffee/image.png',
        imgFull: '/images/catalog/roastedCoffee/imageFull.png',
        description: 'Компания Нью Рефайнинг Груп находится в г. Калининграде и имеет свой склад и представительство в Москве.Завод работает на рынке свежеобжаренного кофе и растворимой продукции более 15 лет.Завод имеет немецкое оборудование марки Probat по обжарке кофе и итальянские агломераторы для производства растворимой продукции.',
    }, {
        num: 5,
        reviews: 9,
        acidicLvl: 7,
        bitterLvl: 5,
        saturatedLvl: 6,
        title: 'Colombia Supremo',
        subtitle: 'Мытая, натуральная, смесь',
        toastingLvl: 4,
        id: 6,
        listOptions: [
            { optionValue: 250, price: 250 },
            { optionValue: 500, price: 500 },
            { optionValue: 1000, price: 1000 },
        ],
        geography: 'Йемен',
        special: 'Микролот',
        typeOfCoffee: 'Арабика',
        imgSrc: '/images/catalog/roastedCoffee/image.png',
        imgFull: '/images/catalog/roastedCoffee/imageFull.png',
        description: 'Компания Нью Рефайнинг Груп находится в г. Калининграде и имеет свой склад и представительство в Москве.Завод работает на рынке свежеобжаренного кофе и растворимой продукции более 15 лет.Завод имеет немецкое оборудование марки Probat по обжарке кофе и итальянские агломераторы для производства растворимой продукции.',
    }, {
        num: 5,
        reviews: 9,
        acidicLvl: 7,
        bitterLvl: 5,
        saturatedLvl: 6,
        title: 'Colombia Supremo',
        subtitle: 'Мытая, натуральная, смесь',
        toastingLvl: 4,
        id: 7,
        listOptions: [
            { optionValue: 250, price: 250 },
            { optionValue: 500, price: 500 },
            { optionValue: 1000, price: 1000 },
        ],
        geography: 'Йемен',
        special: 'Сорт недели',
        typeOfCoffee: 'Арабика',
        imgSrc: '/images/catalog/roastedCoffee/image.png',
        imgFull: '/images/catalog/roastedCoffee/imageFull.png',
        description: 'Компания Нью Рефайнинг Груп находится в г. Калининграде и имеет свой склад и представительство в Москве.Завод работает на рынке свежеобжаренного кофе и растворимой продукции более 15 лет.Завод имеет немецкое оборудование марки Probat по обжарке кофе и итальянские агломераторы для производства растворимой продукции.',
    }, {
        num: 5,
        reviews: 9,
        acidicLvl: 7,
        bitterLvl: 5,
        saturatedLvl: 6,
        title: 'Colombia Supremo',
        subtitle: 'Мытая, натуральная, смесь',
        toastingLvl: 4,
        id: 8,
        listOptions: [
            { optionValue: 250, price: 250 },
            { optionValue: 500, price: 500 },
            { optionValue: 1000, price: 1000 },
        ],
        geography: 'Йемен',
        special: 'Новинка',
        typeOfCoffee: 'Арабика',
        imgSrc: '/images/catalog/roastedCoffee/image.png',
        imgFull: '/images/catalog/roastedCoffee/imageFull.png',
        description: 'Компания Нью Рефайнинг Груп находится в г. Калининграде и имеет свой склад и представительство в Москве.Завод работает на рынке свежеобжаренного кофе и растворимой продукции более 15 лет.Завод имеет немецкое оборудование марки Probat по обжарке кофе и итальянские агломераторы для производства растворимой продукции.',
    }, {
        num: 5,
        reviews: 9,
        acidicLvl: 7,
        bitterLvl: 5,
        saturatedLvl: 6,
        title: 'Colombia Supremo',
        subtitle: 'Мытая, натуральная, смесь',
        toastingLvl: 4,
        id: 9,
        listOptions: [
            { optionValue: 250, price: 250 },
            { optionValue: 500, price: 500 },
            { optionValue: 1000, price: 1000 },
        ],
        geography: 'Йемен',
        special: 'Популярное',
        typeOfCoffee: 'Арабика',
        imgSrc: '/images/catalog/roastedCoffee/image.png',
        imgFull: '/images/catalog/roastedCoffee/imageFull.png',
        description: 'Компания Нью Рефайнинг Груп находится в г. Калининграде и имеет свой склад и представительство в Москве.Завод работает на рынке свежеобжаренного кофе и растворимой продукции более 15 лет.Завод имеет немецкое оборудование марки Probat по обжарке кофе и итальянские агломераторы для производства растворимой продукции.',
    },
]

const dataRoastedСoffeeDiscount = [
    {
        num: 4,
        reviews: 8,
        acidicLvl: 7,
        bitterLvl: 5,
        saturatedLvl: 6,
        title: 'Colombia Supremo',
        subtitle: 'Мытая, натуральная, смесь',
        toastingLvl: 3,
        id: 1,
        listOptions: [
            { optionValue: 250, price: 250, oldPrice: 350 },
            { optionValue: 500, price: 500, oldPrice: 650 },
            { optionValue: 1000, price: 1000, oldPrice: 1150 },
        ],
        geography: 'Африка',
        special: 'Скидки',
        typeOfCoffee: 'Робуста',
        imgSrc: '/images/catalog/roastedCoffee/image.png',
        imgFull: '/images/catalog/roastedCoffee/imageFull.png',
        description: 'Компания Нью Рефайнинг Груп находится в г. Калининграде и имеет свой склад и представительство в Москве.Завод работает на рынке свежеобжаренного кофе и растворимой продукции более 15 лет.Завод имеет немецкое оборудование марки Probat по обжарке кофе и итальянские агломераторы для производства растворимой продукции.',

    }, {
        num: 3,
        reviews: 8,
        acidicLvl: 8,
        bitterLvl: 5,
        saturatedLvl: 6,
        title: 'Colombia Supremo',
        subtitle: 'Мытая, натуральная, смесь',
        toastingLvl: 3,
        id: 2,
        listOptions: [
            { optionValue: 250, price: 250, oldPrice: 350 },
            { optionValue: 500, price: 500, oldPrice: 650 },
            { optionValue: 1000, price: 1000, oldPrice: 1150 },
        ],
        geography: 'Африка',
        special: 'Скидки',
        typeOfCoffee: 'Робуста',
        imgSrc: '/images/catalog/roastedCoffee/image.png',
        imgFull: '/images/catalog/roastedCoffee/imageFull.png',
        description: 'Компания Нью Рефайнинг Груп находится в г. Калининграде и имеет свой склад и представительство в Москве.Завод работает на рынке свежеобжаренного кофе и растворимой продукции более 15 лет.Завод имеет немецкое оборудование марки Probat по обжарке кофе и итальянские агломераторы для производства растворимой продукции.',

    }, {
        num: 1,
        reviews: 8,
        acidicLvl: 5,
        bitterLvl: 5,
        saturatedLvl: 6,
        title: 'Colombia Supremo',
        subtitle: 'Мытая, натуральная, смесь',
        toastingLvl: 3,
        id: 3,
        listOptions: [
            { optionValue: 250, price: 250, oldPrice: 350 },
            { optionValue: 500, price: 500, oldPrice: 650 },
            { optionValue: 1000, price: 1000, oldPrice: 1150 },
        ],
        geography: 'Африка',
        special: 'Скидки',
        typeOfCoffee: 'Робуста',
        imgSrc: '/images/catalog/roastedCoffee/image.png',
        imgFull: '/images/catalog/roastedCoffee/imageFull.png',
        description: 'Компания Нью Рефайнинг Груп находится в г. Калининграде и имеет свой склад и представительство в Москве.Завод работает на рынке свежеобжаренного кофе и растворимой продукции более 15 лет.Завод имеет немецкое оборудование марки Probat по обжарке кофе и итальянские агломераторы для производства растворимой продукции.',

    },
    {
        num: 4,
        reviews: 8,
        acidicLvl: 7,
        bitterLvl: 5,
        saturatedLvl: 6,
        title: 'Colombia Supremo',
        subtitle: 'Мытая, натуральная, смесь',
        toastingLvl: 3,
        id: 10,
        listOptions: [
            { optionValue: 250, price: 250, oldPrice: 350 },
            { optionValue: 500, price: 500, oldPrice: 650 },
            { optionValue: 1000, price: 1000, oldPrice: 1150 },
        ],
        geography: 'Африка',
        special: 'Скидки',
        typeOfCoffee: 'Робуста',
        imgSrc: '/images/catalog/roastedCoffee/image.png',
        imgFull: '/images/catalog/roastedCoffee/imageFull.png',
        description: 'Компания Нью Рефайнинг Груп находится в г. Калининграде и имеет свой склад и представительство в Москве.Завод работает на рынке свежеобжаренного кофе и растворимой продукции более 15 лет.Завод имеет немецкое оборудование марки Probat по обжарке кофе и итальянские агломераторы для производства растворимой продукции.',
    },
]

const allDataRoastedСoffee = [...dataRoastedСoffee, ...dataRoastedСoffeeDiscount].sort(() => Math.random() - 0.5)

module.exports = { dataRoastedСoffee, dataRoastedСoffeeDiscount, allDataRoastedСoffee }